### PR TITLE
Remove dependency

### PR DESCRIPTION
**Pull request by JosephDev**
fix dependency error while installing. import package to mark version information is brake install process.

### CODE REVIEW

**Comment by alertedsnake** [comment]
Can you provide some information on how this actually breaks things?  I don't see the reason for this.

**Comment by alertedsnake** [comment]
Also, why are you doing this on my branch?  Seems like this is a change that should be made to master, and then I'll rebase my branch.

**Comment by JosephDev** [comment]
@alertedsnake About the PR, I am sorry if you are not uncomfortable with my PR. I do this on your branch because I waiting for your PR is merged onto master but never happened. So, I forked your branch.

about the code, in setup.py, `import packagetrack` is brake installing because `fedex` package is not installed yet. so I remove version information into setup.py from package file.

**Comment by alertedsnake** [comment]
Oh I see.  I wonder why the author did that originally.

Still, you're not making changes specific to my branch, and I'm not the maintainer of this thing, so you should probably make your changes based on the parent master branch.

**Comment by JosephDev** [comment]
@alertedsnake haha. um... okay. I will do working on my repo. I made PR to your branch because you accept my PR once. :)

**Pull request closed without merging**
